In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [20]:
data = pd.read_csv('../../../Amazon.csv')
print(data.shape) #print the (rows,cols) of matrix
data.head(50) #print 1st 50 rows

(455000, 13)


Unnamed: 0      Id   ProductId          UserId  \
0       138806  138807  B000E63LME  A1CQGW1AOD0LF2   
1       469680  469681  B004ZIH4KM  A37S7U1OX2MCWI   
2       238202  238203  B003ZXE9QA  A2OM6G73E64EQ9   
3       485307  485308  B001RVFERK  A25W349EE97NBK   
4       375283  375284  B000OQZNTS  A3CPPW0HUC07YS   
5       530491  530492  B001E5DX90  A26XS571YR9XPF   
6       355114  355115  B000IGAE66   A1WFG6OC3PPGZ   
7       565582  565583  B002GKEK7G  A119CG9WIR9PEG   
8       173265  173266  B000XZBXP8  A26F4DH22KS0ZC   
9       500973  500974  B001EQ5GZI  A206PQUGK87WZ7   
10      201170  201171  B00395570G  A2V2SL3JIOXYVM   
11       39804   39805  B000E7QYNG  A18VNDSPWOOKNP   
12      105099  105100  B0036VLZDQ  A1WR5TWGNODAHA   
13      563874  563875  B007JFMH8M  A1YJMG0QJXZLD4   
14      402723  402724  B001ELL288   ANTUU87TDRHT4   
15      262950  262951  B0000D1728   ANNHY2DW6MNFI   
16      202052  202053  B00028QDMY  A3N8RB943DMSH7   
17      449557  449558  B003P9WU6K  A14QH5E4GBNG19   
18      508228  508229  B006N3IE6A  A29BHW9YT2FZ77   
19      446338  446339  B001EPQVUI  A2CXFW8ONAYAH2   
20      138739  138740  B001E6GFTY  A31N6KB160O508   
21       11483   11484  B000GZUA6I  A36FIBWPU7FBEM   
22      408286  408287  B005NYXE24  A1W1712VKVBF1B   
23      269873  269874  B0045IPVLG   AC6MZWYBC7ADL   
24      270071  270072  B000LRIFU4  A257A9BE64Z1BY   
25      406022  406023  B000WW6VZO  A20W8WOINFTABS   
26      102394  102395  B00772YD7U   AX2D1DE4WQU6W   
27      185039  185040  B002ZH6XYI  A2GZ3O8AHD3PI2   
28      270238  270239  B002AQ0OS0   A1X1WV2DHHJ0R   
29      153507  153508  B000ILEITA  A3QCLG42FKIO67   
30        1867    1868  B001RVFDOO   A2CZ5N1OS9R63   
31      152403  152404  B000LKZD4W  A3N4ADZDBUSTZK   
32      134064  134065  B002AUCELQ  A2X1XBJOQXQ3W8   
33      266198  266199  B001D9RVMM  A3QZ6JT0R1OWEC   
34      509649  509650  B001GL6GBE  A2CTIAQMDM6LDP   
35      139156  139157  B000FPKX5C  A2BV4DT6AP1RAC   
36      144332  144333  B0029U7O0S  A2EFU66QLIUUL0   
37       69233   69234  B0018KR8V0   AUF2WEJPK910V   
38      177760  177761  B000HDH0HQ  A27F0F7ODCSH3T   
39      250928  250929  B004DOXI9O  A1CFU5XJXN3PV4   
40      189606  189607  B001EO5Q64  A1KLM9I4DP4ASM   
41      168254  168255  B005VOOKS8   A1MKPMJPD22YY   
42      376044  376045  B0018N38P2   AQ3M9XRADAMNN   
43       19115   19116  B003WT71MG  A1VXZJVVLQNX9G   
44      420897  420898  B00028LDII  A1LCFFLK7SWZ48   
45      489148  489149  B005K4Q1YA  A2FBB7EGBLFN8W   
46      543208  543209  B005XD1FBM   ACNQRJWEE2IXX   
47      108789  108790  B000HBY6UW  A30HU2RBBFZIFH   
48      260392  260393  B000NMJWZO   AVNJ9WIYDVE17   
49      399030  399031  B0038B3AGO  A1Q3SNTUQ5M68P   

                              ProfileName  HelpfulnessNumerator  \
0                        Alena K. "Alena"                     1   
1                              Becky Cole                     0   
2                                    jeff                     0   
3                                Tangent4                     1   
4                             Amy Nicolai                     0   
5                                Briana B                     0   
6                                N. Myhre                     0   
7                               SWalling1                     0   
8                                  DocT65                     1   
9                                N. Wells                     0   
10                                 doodle                     0   
11                                 Kabuki                     2   
12                               Katie R.                     0   
13                              Rosemarie                     0   
14                              B. Seeman                     0   
15                                  David                     3   
16  Alisa Marie Fleming "GoDairyFree.org"                     3   
17               P. Payne "Loves Perfume"  

In [ ]:
# features from Amazon.csv to add to feature set

In [23]:
# add review length col to dataset (pandas)
data['ReviewLen'] = data['Text'].str.len()

In [25]:
# add col for extreme scores:
# -1 for 1 star, 1 for 5 stars, and 0 for anything else
data['BigScore'] = 0 # set all rows to 0
data.ix[data['Score'] == 1, 'BigScore'] = -1 # if score is 1, set to -1
data.ix[data['Score'] == 5, 'BigScore'] = 1 # if score is 5, set to 1

In [42]:
# convert unix timestamp to datetime
data['DateTime'] = pd.to_datetime(data['Time'], unit='s')
# all these Times are midnight of a day

# find day of week (0-6, Mon-Sun)
data['DayOfWeek'] = data['DateTime'].dt.weekday
data['Month'] = data['DateTime'].dt.month
data['Year'] = data['DateTime'].dt.year

In [43]:
# # order of this review on item (first = 0, second = 1, etc.)
# data['ReviewOrder'] = 0
# # for each row
# # group data by ProductId and then order by timestamp
# # then save order to 'ReviewOrder'
# productId_group = data.groupby('ProductId')

In [50]:
data.head(50)

Unnamed: 0      Id   ProductId          UserId  \
0       138806  138807  B000E63LME  A1CQGW1AOD0LF2   
1       469680  469681  B004ZIH4KM  A37S7U1OX2MCWI   
2       238202  238203  B003ZXE9QA  A2OM6G73E64EQ9   
3       485307  485308  B001RVFERK  A25W349EE97NBK   
4       375283  375284  B000OQZNTS  A3CPPW0HUC07YS   
5       530491  530492  B001E5DX90  A26XS571YR9XPF   
6       355114  355115  B000IGAE66   A1WFG6OC3PPGZ   
7       565582  565583  B002GKEK7G  A119CG9WIR9PEG   
8       173265  173266  B000XZBXP8  A26F4DH22KS0ZC   
9       500973  500974  B001EQ5GZI  A206PQUGK87WZ7   
10      201170  201171  B00395570G  A2V2SL3JIOXYVM   
11       39804   39805  B000E7QYNG  A18VNDSPWOOKNP   
12      105099  105100  B0036VLZDQ  A1WR5TWGNODAHA   
13      563874  563875  B007JFMH8M  A1YJMG0QJXZLD4   
14      402723  402724  B001ELL288   ANTUU87TDRHT4   
15      262950  262951  B0000D1728   ANNHY2DW6MNFI   
16      202052  202053  B00028QDMY  A3N8RB943DMSH7   
17      449557  449558  B003P9WU6K  A14QH5E4GBNG19   
18      508228  508229  B006N3IE6A  A29BHW9YT2FZ77   
19      446338  446339  B001EPQVUI  A2CXFW8ONAYAH2   
20      138739  138740  B001E6GFTY  A31N6KB160O508   
21       11483   11484  B000GZUA6I  A36FIBWPU7FBEM   
22      408286  408287  B005NYXE24  A1W1712VKVBF1B   
23      269873  269874  B0045IPVLG   AC6MZWYBC7ADL   
24      270071  270072  B000LRIFU4  A257A9BE64Z1BY   
25      406022  406023  B000WW6VZO  A20W8WOINFTABS   
26      102394  102395  B00772YD7U   AX2D1DE4WQU6W   
27      185039  185040  B002ZH6XYI  A2GZ3O8AHD3PI2   
28      270238  270239  B002AQ0OS0   A1X1WV2DHHJ0R   
29      153507  153508  B000ILEITA  A3QCLG42FKIO67   
30        1867    1868  B001RVFDOO   A2CZ5N1OS9R63   
31      152403  152404  B000LKZD4W  A3N4ADZDBUSTZK   
32      134064  134065  B002AUCELQ  A2X1XBJOQXQ3W8   
33      266198  266199  B001D9RVMM  A3QZ6JT0R1OWEC   
34      509649  509650  B001GL6GBE  A2CTIAQMDM6LDP   
35      139156  139157  B000FPKX5C  A2BV4DT6AP1RAC   
36      144332  144333  B0029U7O0S  A2EFU66QLIUUL0   
37       69233   69234  B0018KR8V0   AUF2WEJPK910V   
38      177760  177761  B000HDH0HQ  A27F0F7ODCSH3T   
39      250928  250929  B004DOXI9O  A1CFU5XJXN3PV4   
40      189606  189607  B001EO5Q64  A1KLM9I4DP4ASM   
41      168254  168255  B005VOOKS8   A1MKPMJPD22YY   
42      376044  376045  B0018N38P2   AQ3M9XRADAMNN   
43       19115   19116  B003WT71MG  A1VXZJVVLQNX9G   
44      420897  420898  B00028LDII  A1LCFFLK7SWZ48   
45      489148  489149  B005K4Q1YA  A2FBB7EGBLFN8W   
46      543208  543209  B005XD1FBM   ACNQRJWEE2IXX   
47      108789  108790  B000HBY6UW  A30HU2RBBFZIFH   
48      260392  260393  B000NMJWZO   AVNJ9WIYDVE17   
49      399030  399031  B0038B3AGO  A1Q3SNTUQ5M68P   

                              ProfileName  HelpfulnessNumerator  \
0                        Alena K. "Alena"                     1   
1                              Becky Cole                     0   
2                                    jeff                     0   
3                                Tangent4                     1   
4                             Amy Nicolai                     0   
5                                Briana B                     0   
6                                N. Myhre                     0   
7                               SWalling1                     0   
8                                  DocT65                     1   
9                                N. Wells                     0   
10                                 doodle                     0   
11                                 Kabuki                     2   
12                               Katie R.                     0   
13                              Rosemarie                     0   
14                              B. Seeman                     0   
15                                  David                     3   
16  Alisa Marie Fleming "GoDairyFree.org"                     3   
17               P. Payne "Loves Perfume"  

In [54]:
# convert score + reviewLen cols to vectors
# [:, 7] denotes all rows in col 7

XScore = data.iloc[:, 7].values.reshape(data.shape[0], 1)
XReviewLen = data.iloc[:, 13].values.reshape(data.shape[0], 1)
XBigScore = data.iloc[:, 14].values.reshape(data.shape[0], 1)
XDayOfWeek = data.iloc[:, 16].values.reshape(data.shape[0], 1)
XMonth = data.iloc[:, 17].values.reshape(data.shape[0], 1)
XYear = data.iloc[:, 18].values.reshape(data.shape[0], 1)

# concatenate to numpy dataset
XToAdd = np.concatenate((XScore, XReviewLen, XBigScore, XDayOfWeek, XMonth, XYear), axis=1)

print(XToAdd)

[[   2  206    0    2    1 2011]
 [   5  125    1    1   10 2012]
 [   5  678    1    2    2 2012]
 ..., 
 [   5  283    1    0    8 2011]
 [   5  266    1    1    6 2010]
 [   5  275    1    3    5 2012]]


In [55]:
# vectorize Bag of Words from review text; as sparse matrix
from sklearn.feature_extraction.text import HashingVectorizer
# Text
hvText = HashingVectorizer(stop_words='english', n_features=2 ** 17, non_negative=True)
XText = hvText.transform(data.Text)
# Summary
# hvSummary = HashingVectorizer(stop_words='english', n_features=2 ** 17, non_negative=True)
# XSummary = hvSummary.transform(data.Summary)

In [52]:
# Tf-idf transformer with pipeline from hash vectorizer?
#### example ####
# hashing = HashingVectorizer(non_negative=True, norm=None)
# tfidf = TfidfTransformer()
# hashing_tfidf = Pipeline([("hashing", hashing), ("tidf", tfidf)])

In [56]:
# convert additional features to sparse matrix and concatenate onto the bag of words sparse matrix
from scipy.sparse import csr_matrix, hstack
XToAddSparse = csr_matrix(XToAdd)
XFinal = hstack([XText, XToAddSparse])
X = csr_matrix(XFinal)

In [57]:
# size of feature set
print(X.shape)

(455000, 131078)


In [58]:
# define y
y = data.iloc[:, 12].values
y.shape

(455000,)

In [59]:
# create training and test sets
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
         X, y, test_size=0.3, random_state=0)

In [60]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler(with_mean=False)
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [61]:
# report on training and test sets
def print_results():
    print('Error rate on training set: ')
    print((y_train != y_pred).sum() / X_train.shape[0])
    print('Accuracy rate on training set: ')
    print(1 - (y_train != y_pred).sum() / X_train.shape[0])
    print('True positive rate on training set:')
    print(((y_train==True) & (y_pred==True)).sum() / y_train.sum())
    print('**************')
    print('Error rate on test set: ')
    print((y_test != y_pred_test).sum() / X_test.shape[0])
    print('Accuracy rate on test set: ')
    print(1 - (y_test != y_pred_test).sum() / X_test.shape[0])
    print('True positive rate on test set')
    print(((y_test==True) & (y_pred_test==True)).sum() / y_test.sum())
    print('True negative rate on test set')
    print(((y_test==False) & (y_pred_test==False)).sum() / (y_test.shape[0] - y_test.sum()))

In [62]:
# MODEL: SVM, linear
from sklearn import linear_model
clf = linear_model.SGDClassifier()
clf.fit(X_train_std, y_train)
y_pred = clf.fit(X_train_std, y_train).predict(X_train_std)
y_pred_test = clf.predict(X_test_std)
print_results()

Error rate on training set: 
0.0714882260597
Accuracy rate on training set: 
0.92851177394
True positive rate on training set:
0.0197606337179
**************
Error rate on test set: 
0.0740073260073
Accuracy rate on test set: 
0.925992673993
True positive rate on test set
0.00799440391726
True negative rate on test set
0.998616524235


In [63]:
# MODEL: logistic regression
from sklearn import linear_model
clf = linear_model.SGDClassifier(loss='log', n_iter=50, alpha=0.00001)
clf.fit(X_train_std, y_train)
y_pred = clf.fit(X_train_std, y_train).predict(X_train_std)
y_pred_test = clf.predict(X_test_std)
print_results()

Error rate on training set: 
0.0461318681319
Accuracy rate on training set: 
0.953868131868
True positive rate on training set:
0.423454451524
**************
Error rate on test set: 
0.0792527472527
Accuracy rate on test set: 
0.920747252747
True positive rate on test set
0.19036674328
True negative rate on test set
0.97852845612


In [64]:
# MODEL: Naive Bayes
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train_std, y_train)
y_pred = clf.fit(X_train_std, y_train).predict(X_train_std)
y_pred_test = clf.predict(X_test_std)
print_results()

ValueError: Input X must be non-negative

In [65]:
# Perceptron
from sklearn import linear_model
clf = linear_model.SGDClassifier(loss='perceptron')
clf.fit(X_train_std, y_train)
y_pred = clf.fit(X_train_std, y_train).predict(X_train_std)
y_pred_test = clf.predict(X_test_std)
print_results()

Error rate on training set: 
0.0594128728414
Accuracy rate on training set: 
0.940587127159
True positive rate on training set:
0.193344239711
**************
Error rate on test set: 
0.0730476190476
Accuracy rate on test set: 
0.926952380952
True positive rate on test set
0.0840411711802
True negative rate on test set
0.993636011479
